package com.electdept.loadcalculationservice.client;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.stereotype.Component;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.HttpServerErrorException;
import org.springframework.web.client.ResourceAccessException;
import org.springframework.web.client.RestTemplate;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

@Component
public class ProcurementClient {

    private final String procurementUrl;
    private final RestTemplate restTemplate = new RestTemplate();

    public ProcurementClient(@Value("${services.workorder.url}") String procurementUrl) {
        this.procurementUrl = procurementUrl;
    }

    @SuppressWarnings("unchecked")
    public Map<String, Object> createDraftOrder(String bearerToken, Long supplierId, Long warehouseId,
                                                Long skuId, BigDecimal qty, BigDecimal unitPrice) {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        if (bearerToken != null) headers.set(HttpHeaders.AUTHORIZATION, bearerToken);

        Map<String, Object> body = Map.of(
            "supplierId", supplierId,
            "warehouseId", warehouseId,
            "notes", "Auto-generated by replenishment",
            "lines", List.of(Map.of(
                "skuId", skuId,
                "qty", qty,
                "unitPrice", unitPrice
            ))
        );

        HttpEntity<Map<String, Object>> request = new HttpEntity<>(body, headers);
        try {
            ResponseEntity<Map> response = restTemplate.postForEntity(
                procurementUrl + "/workorder/orders", request, Map.class);
            return (Map<String, Object>) response.getBody();
        } catch (HttpClientErrorException | HttpServerErrorException e) {
            throw new RuntimeException("Procurement createDraftOrder failed: " + e.getStatusCode() + " " + e.getResponseBodyAsString(), e);
        } catch (ResourceAccessException e) {
            throw new RuntimeException("ProcurementService is not reachable", e);
        }
    }
}
