spring.application.name=NotificationService
server.port=9014

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.datasource.url=jdbc:postgresql://localhost:5432/ElectDeptSoftware
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=notification

services.auth.url=http://localhost:9001

security.jwt.secret=Xk9#mP2$vL5nQ8wR3jF6hT1yU4nN7cA0sD9fG2iK5oM8pE3xZ6vW1qJ4rH7tY0uI
security.jwt.expiry-minutes=60
spring.datasource.hikari.maximum-pool-size=3
